name: Atualizar Sesc TV (1h)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Buscar link atual do Sesc TV
        run: |
          PAGE_URL="https://www.sesctv.org.br/ao-vivo/"
          NOVO_LINK=$(curl -s "$PAGE_URL" | grep -o 'https://[^"]*singularcdn[^"]*m3u8[^"]*' | head -n 1)

          if [ -z "$NOVO_LINK" ]; then
            echo "❌ Link do Sesc não encontrado"
            exit 1
          fi

          echo "✅ Link encontrado:"
          echo "$NOVO_LINK"

          sed -i "s|{{SESC_TV_LINK}}|$NOVO_LINK|g" lista.m3u

      - name: Salvar atualização
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add lista.m3u
          git commit -m "Atualização automática Sesc TV" || echo "Nada para atualizar"
          git push